(function(a){function b(a){return a<10?"0"+a:a}Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+b(this.getUTCMonth())+"-"+b(this.getUTCDate())};var c=/["\\\x00-\x1f\x7f-\x9f]/g,e={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};a.quoteString=function(a){if(c.test(a))return'"'+a.replace(c,function(a){var i=e[a];if(typeof i==="string")return i;i=a.charCodeAt();return"\\u00"+Math.floor(i/16).toString(16)+(i%16).toString(16)})+'"';return'"'+a+'"'};
a.toJSON=function(b,c){var i=typeof b;if(i=="undefined")return"undefined";else if(i=="number"||i=="boolean")return b+"";else if(b===null)return"null";if(i=="string")return a.quoteString(b);if(i=="object"&&typeof b.toJSON=="function")return b.toJSON(c);if(i!="function"&&typeof b.length=="number"){for(var j=[],o=0;o<b.length;o++)j.push(a.toJSON(b[o],c));return c?"["+j.join(",")+"]":"["+j.join(", ")+"]"}if(i=="function")throw new TypeError("Unable to convert object of type 'function' to json.");j=[];
for(o in b){i=typeof o;if(i=="number")i='"'+o+'"';else if(i=="string")i=a.quoteString(o);else continue;var e=a.toJSON(b[o],c);typeof e=="string"&&(c?j.push(i+":"+e):j.push(i+": "+e))}return"{"+j.join(", ")+"}"};a.compactJSON=function(b){return a.toJSON(b,!0)};a.evalJSON=function(a){return eval("("+a+")")};a.secureEvalJSON=function(a){var b;b=a.replace(/\\["\\\/bfnrtu]/g,"@");b=b.replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]");b=b.replace(/(?:^|:|,)(?:\s*\[)+/g,"");
if(/^[\],:{}\s]*$/.test(b))return eval("("+a+")");else throw new SyntaxError("Error parsing JSON, source is not valid.");}})(jQuery);
(function(a){function b(){return function(b){if(b.jquery){var c={};c[0]=jQuery;a.map(b.jquery,function(b){var i=b[0],e=b[1],g=b[2],b=b[3];if(typeof b=="string")b=a.unsafe(b);else for(var h=0;b.length&&h<b.length;h++)b[h]=a.unsafe(b[h]);g=="call"?c[e]=c[i].apply(c[i]._obj,b):g=="attr"?(c[e]=c[i][b],c[e]?c[e]._obj=c[i]:a.debug("unrecognized")):a.debug("unrecognized")})}}}a.log=function(a){window.console?window.console.debug?window.console.debug(a):window.console.log&&window.console.log(a):alert(a)};
a.debug=function(b){if(a.with_default(reddit.debug,!1))return a.log(b)};a.fn.debug=function(){a.debug(a(this));return a(this)};a.redirect=function(a){window.location=a};a.fn.redirect=function(b){a(this).filter("form").find(".status").show().html("redirecting...");if(a(this).attr("target")=="_top"){for(var c=window;c!=c.parent;)c=c.parent;c.location=b}else a.redirect(b);return a(this)};a.refresh=function(){window.location.reload(!0)};a.defined=function(a){return typeof a!="undefined"};a.with_default=
function(b,c){return a.defined(b)?b:c};a.websafe=function(a){typeof a=="string"&&(a=a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/>/g,"&gt;").replace(/</g,"&lt;"));return a||""};a.unsafe=function(a){typeof a=="string"&&(a=a.replace(/&quot;/g,'"').replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&"));return a||""};a.uniq=function(a,b){for(var c=[],e={},g=b?b:a.length,h=0;h<a.length&&c.length<g;h++)e[a[h]]||(e[a[h]]=!0,c.push(a[h]));return c};(function(b,c){a.fn.show=function(c,
j){a(this).trigger("onshow");return b.call(this,c,j)};a.fn.hide=function(b,i){a(this).trigger("onhide");return c.call(this,b,i)}})(a.fn.show,a.fn.hide);var c={};a.request=function(i,j,e,g,h,m,k){var l=i,n=e;if(!(rate_limit(i)||window!=window.top&&!reddit.cnameframe&&!reddit.external_frame)){if(!(n=!a.with_default(g,!1)))n=c[l]?!1:c[l]=!0;g=n;j=a.with_default(j,{});e=a.with_default(e,b(l));h=a.with_default(h,"json");typeof e!="function"&&(e=b(l));n=function(a){delete c[l];return e(a)};errorhandler_in=
a.with_default(k,function(){});k=function(a){delete c[l];return errorhandler_in(a)};m=a.with_default(m,!1);if(reddit.post_site)j.r=reddit.post_site;if(reddit.cnameframe)j.cnameframe=1;if(reddit.logged)j.uh=reddit.modhash;j.renderstyle=reddit.renderstyle;g&&a.ajax({type:m?"GET":"POST",url:"/api/"+i,data:j,success:n,error:k,dataType:h})}};rate_limit=function(){var b={vote:333,comment:5E3,ignore:0,ban:0,unban:0,assignad:0},c={},e=a.defined,g=a.with_default,h=Date;return function(a){var k=new h,l=c[a],
n=g(b[a],333);c[a]=k;return e(l)&&k-l<n}}();a.fn.vote=function(b,c,e,g){if(reddit.logged){if(a(this).hasClass("arrow")){var h=a(this).hasClass("up")?1:a(this).hasClass("down")?-1:0,m=a(this).all_things_by_id(),k=m.children().not(".child").find(".arrow"),l=h==1?"up":"upmod";k.filter("."+l).removeClass(l).addClass(h==1?"upmod":"up");l=h==-1?"down":"downmod";k.filter("."+l).removeClass(l).addClass(h==-1?"downmod":"down");reddit.logged&&(m.each(function(){var b=a(this).find(".entry:first, .midcol:first");
h>0?b.addClass("likes").removeClass("dislikes unvoted"):h<0?b.addClass("dislikes").removeClass("likes unvoted"):b.addClass("unvoted").removeClass("likes dislikes")}),a.defined(g)||(g=m.filter(":first").thing_id(),b+=e?"":"-"+g,a.request("vote",{id:g,dir:h,vh:b})));c&&c(m,h)}}else showcover(!0,"vote_"+a(this).thing_id());e&&e.stopPropagation()};a.fn.show_unvotable_message=function(){a(this).thing().find(".entry:first .unvotable-message").css("display","inline-block")};a.fn.thing=function(){return this.parents(".thing:first")};
a.fn.all_things_by_id=function(){return this.thing().add(a.things(this.thing_id()))};a.fn.thing_id=function(b){var b=a.with_default(b,"thing"),c=this.hasClass("thing")?this:this.thing();b!="thing"&&(c=c.find("."+b+":first"));if(c.length)return b=a.grep(c.get(0).className.match(/\S+/g),function(a){return a.match(/^id-/)}),b.length?b[0].slice(3,b[0].length):"";return""};a.things=function(){var b=a.map(arguments,function(a){return".thing.id-"+a}).join(", ");return a(b)};a.fn.same_author=function(){var b=
a(this).thing_id("author"),c=[];a(".author.id-"+b).each(function(){c.push(".thing.id-"+a(this).thing_id())});return a(c.join(", "))};a.fn.things=function(){return this.find(a.map(arguments,function(a){return".thing.id-"+a}).join(", "))};a.listing=function(b){b=b||"";if(b.slice(0,1)=="#"||b.slice(0,1)==".")b=b.slice(1,b.length);var c=b;b.slice(0,9)!="siteTable"?c="siteTable"+(b?"_"+b:""):b=b.slice(10,b.length);var e=a("#"+c).filter(":first");e.length==0&&(e=a.things(b).find(".child").append(document.createElement("div")).children(":last").addClass("sitetable").attr("id",
c));return e};var e=function(){};a.fn.set_thing_init=function(b){e=b;a(this).find(".thing:not(.stub)").each(function(){b(this)})};a.fn.new_thing_child=function(b,c){var e=this.thing_id(),g=c?a.listing(e):this.thing().find(".child:first");return(typeof b=="string"?g.prepend(b).children(":first"):b.hide().prependTo(g).show().find('input[name="parent"]').val(e).end()).randomize_ids()};a.fn.randomize_ids=function(){var b=(Math.random()+"").split(".")[1];a(this).find("*[id]").each(function(){a(this).attr("id",
a(this).attr("id")+b)}).end().find("label").each(function(){a(this).attr("for",a(this).attr("for")+b)});return a(this)};a.fn.replace_things=function(b,c,g,h){var p=a(".midcol:visible:first").css("width");a(".rank:visible:first").css("width");var m=this;return a.map(b,function(b){var i=b.data,b=a(m).things(i.id);h&&(b=b.filter(".stub"));if(b.length==0){var n=a.things(i.parent);n.length&&(b=a("<div></div>"),n.find(".child:first").append(b))}b.after(a.unsafe(i.content));i=b.next();a.defined(p)&&i.find(".midcol").css("width",
p).end().find(".rank").css("width",p);c&&(i.show().children(".midcol, .entry").hide().end().children(".child:first").html(b.children(".child:first").remove().html()).end(),g&&(b.hide(),i.children(".midcol, .entry").show()),i.find(".rank:first").html(b.find(".rank:first").html()));g?(b.hide(),c?i.children(".midcol, .entry").show():i.show()):i.hide();b.remove();e(i);return i})};a.insert_things=function(b,c){return a.map(b,function(b){var b=b.data,i=a(".midcol:visible:first").css("width"),g=a(".rank:visible:first").css("width"),
h=a.listing(b.parent),h=c?h.append(a.unsafe(b.content)).children(".thing:last"):h.prepend(a.unsafe(b.content)).children(".thing:first");h.find(".midcol").css("width",i);h.find(".rank").css("width",g);e(h.hide().show());return h})};a.fn.delete_table_row=function(b){var c=this.parents("tr:first").get(0),e=this.parents("table").get(0);c?a(c).fadeOut(function(){e.deleteRow(c.rowIndex);b&&b()}):b&&b()};a.fn.insert_table_rows=function(b,c){var e=this.is("table")?this.filter("table"):this.parents("table:first");
a.map(e.get(),function(e){a.map(b,function(b){var g=c;g<0&&(g=Math.max(e.rows.length+g+1,0));var g=Math.min(g,e.rows.length),i=e.insertRow(g);a(i).hide().attr("id",b.id).addClass(b.css_class);a.map(b.cells,function(b){a(i.insertCell(i.cells.length)).html(a.unsafe(b))});a(i).fadeIn()})});return this};a.set_tracker=function(b,c,e){reddit.trackers[b]={show:c,click:e};a.things(b).filter(":visible").show()};a.fn.captcha=function(a){var b=this.find(".capimage");a&&b.attr("src","http://"+reddit.ajax_domain+
"/captcha/"+a+".png").parents("form").find('input[name="iden"]').val(a);return b};a.fn.insertAtCursor=function(b){return a(this).filter("textarea").each(function(){var c=a(this).get(0),e=c.scrollTop;if(document.selection)c.focus(),document.selection.createRange().text=b;else if(c.selectionStart){var g=c.selectionStart;c.value=c.value.substring(0,c.selectionStart)+b+c.value.substring(c.selectionEnd,c.value.length);g+=b.length;c.setSelectionRange(g,g)}else c.value+=b;if(c.scrollHeight)c.scrollTop=e;
a(this).focus()}).end()};a.fn.select_line=function(b){return a(this).filter("textarea").each(function(){var c="\n",e=1,g=0;a.browser.msie&&(c="\r",e=0,g=1);for(var c=a(this).val().split(c),h=0;h<b-1;h++)g+=c[h].length+e;h=g;b<=c.length&&(h+=c[b-1].length+e);a(this).focus();this.createTextRange?(e=this.createTextRange(),e.move("character",g),g=this.createTextRange(),g.move("character",h),e.setEndPoint("StartToEnd",g),e.select()):this.selectionStart&&this.setSelectionRange(g,h);if(this.scrollHeight)this.scrollTop=
(b-2)*(this.scrollHeight/c.length)})};a.apply_stylesheet=function(b){var c=a("head").children("link[title], style[title]").filter(":first").attr("title")||"preferred stylesheet";if(document.styleSheets[0].cssText)for(var e=document.styleSheets,g=0;g<e.length;g++){if(e[g].title==c){e[g].cssText=b;break}}else a("head").children('*[title="'+c+'"]').remove(),a("head").append("<style type='text/css' media='screen' title='"+c+"'>"+b+"</style>")};a.rehighlight_new_comments=function(){checked=a(".comment-visits-box input:checked");
checked.length>0&&highlight_new_comments(checked[0].value)};var g;a.default_cookie_domain=function(b){a.defined(b)&&(g=b);return g};var h="_";a.cookie_name_prefix=function(b){a.defined(b)&&(h=b+"_");return h};a.cookie_test=function(){var b=(Math.random()+"").split(".")[1];a.cookie_write({name:"test",data:b});if(a.cookie_read("test").data==b)return a.cookie_erase("test"),!0};a.cookie_erase=function(b){b.data="";b.expires=-1;a.cookie_write(b)};a.cookie_write=function(b){if(b.name){var c=a.with_default(b.data,
""),c=typeof c=="string"?c:a.toJSON(c),c=h+b.name+"="+escape(c);if(a.defined(b.expires)){var e=b.expires;if(typeof e=="number"){var q=new Date;q.setTime(q.getTime()+e*864E5);e=q}a.defined(e.toGMTString)&&(e=e.toGMTString());c+="; expires="+e}e=a.with_default(b.domain,g);a.defined(e)&&(c+="; domain="+e);c+="; path="+a.with_default(b.path,"/");document.cookie=c}};a.cookie_read=function(b,c){for(var e=(c||h)+b+"=",g=document.cookie.split(";"),p="",m=g.length-1;m>=0;m--){for(var k=g[m];k.charAt(0)==" ";)k=
k.substring(1,k.length);if(k.indexOf(e)==0){p=unescape(k.substring(e.length,k.length));try{p=a.secureEvalJSON(p)}catch(l){}break}}return{name:b,data:p}}})(jQuery);r={};function open_menu(a){$(a).siblings(".drop-choices").not(".inuse").css("top",a.offsetHeight+"px").each(function(){$(this).css("left",$(a).position().left+"px").css("top",$(a).height()+$(a).position().top+"px")}).addClass("active inuse")}
function close_menus(a){$(".drop-choices.inuse").not(".active").removeClass("inuse");$(".drop-choices.active").removeClass("active");$(a.target).closest("#search").length==0&&($("#moresearchinfo").slideUp(),$("#searchexpando").length==1?$("#searchexpando").slideUp(function(){$("#search_showmore").parent().show()}):$("#search_showmore").parent().show())}function hover_open_menu(){}function update_user(a){try{var b=$(a).find('input[name="user"]').val();a.action+="/"+b}catch(c){}return!0}
function post_user(a,b){var c=$(a).find('input[name="user"]').val();return c==null?post_form(a,b):post_form(a,b+"/"+c)}function post_form(a,b,c,e,g){try{return c==null&&(c=function(){return reddit.status_msg.submitting}),$(a).find(".error").not(".status").hide(),$(a).find(".status").html(c(a)).show(),simple_post_form(a,b,{},g)}catch(h){return!1}}
function get_form_fields(a,b,c){b=b||{};c||(c=function(){return!0});$(a).find("select, input, textarea").not(".gray, :disabled").each(function(){var a=$(this).attr("type");if(c(this)&&(a!="radio"&&a!="checkbox"||$(this).is(":checked")))b[$(this).attr("name")]=$(this).val()});if(b.id==null)b.id=$(a).attr("id")?"#"+$(a).attr("id"):"";return b}function form_error(a){return function(b){$(a).find(".status").html("an error occurred while posting (status: "+b.status+")").end()}}
function simple_post_form(a,b,c,e){$.request(b,get_form_fields(a,c),null,e,"json",!1,form_error(a));return!1}function post_pseudo_form(a,b,c){$(a).find(".error").not(".status").hide();$(a).find(".status").html(reddit.status_msg.submitting).show();$.request(b,get_form_fields(a,{},function(b){b=$(b).parents("form:first");return b.length==0||b.get(0)==$(a).get(0)}),null,c,"json",!1,form_error(a));return!1}
function emptyInput(a,b){!$(a).val()||$(a).val()==b?$(a).addClass("gray").val(b).attr("rows",3):$(a).focus(function(){})}function showlang(){$(".lang-popup:first").show();return!1}function showcover(a,b){$.request("new_captcha");a?$("#cover_disclaim, #cover_msg").show():$("#cover_disclaim, #cover_msg").hide();$(".login-popup:first").show().find('form input[name="reason"]').val(b||"");return!1}function hidecover(a){$(a).parents(".cover-overlay").hide();return!1}
function deleteRow(a){$(a).delete_table_row()}function change_state(a,b,c,e){var g=$(a).parents("form"),h=g.find('input[name="id"]'),h=h.length?h.val():$(a).thing_id();simple_post_form(g,b,{id:h});c&&c(g.length?g:a,b);$.defined(e)||g.html(g.find('[name="executed"]').val());return!1}function unread_thing(a){a=$(a);a.hasClass("thing")||(a=a.thing());$(a).addClass("new unread")}
function read_thing(a){a=$(a);a.hasClass("thing")||(a=a.thing());$(a).hasClass("new")?$(a).removeClass("new"):$(a).removeClass("unread");$.request("read_message",{id:$(a).thing_id()})}function save_thing(a){$(a).thing().addClass("saved")}function unsave_thing(a){$(a).thing().removeClass("saved")}function click_thing(a){var b=$(a);b.hasClass("thing")||(b=b.thing());b.hasClass("message")&&b.hasClass("recipient")&&(b.hasClass("unread")?b.removeClass("unread"):b.hasClass("new")&&read_thing(a))}
function hide_thing(a){$(a).thing().fadeOut(function(){$(this).toggleClass("hidden")})}function toggle_label(a,b,c){$(a).parent().find(".option").toggle();$(a)[0].onclick=function(){return toggle_label(a,c,b)};b&&b(a)}function toggle(a,b,c){var e=$(a).parent().andSelf().filter(".option").removeClass("active").siblings().addClass("active").get(0);if(c&&!e.onclick)e.onclick=function(){return toggle(e,c,b)};b&&b(a);return!1}
function cancelToggleForm(a,b,c,e){c&&$(a).filter("button").length&&(c=$(a).thing().find(c).children(":visible").filter(":first"),toggle(c));$(a).thing().find(b).each(function(){e&&e($(this));$(this).hide().remove()});return!1}
function get_organic(a,b){var c=$(a).parents(".organic-listing"),e=c.find(".thing:visible");if(c.find(":animated").length)return!1;var g;b?(g=e.nextAll(".thing:not(.stub)").filter(":first"),g.length==0&&(g=e.siblings(".thing:not(.stub)").filter(":first"))):(g=e.prevAll(".thing:not(.stub)").filter(":first"),g.length==0&&(g=e.siblings(".thing:not(.stub)").filter(":last")));e.fadeOut("fast",function(){g.length&&g.fadeIn("fast",function(){for(var a=e,g=[],j=0;j<10;j++)if(a=b?a.nextAll(".thing:first"):
a.prevAll(".thing:first"),a.length==0&&(a=a.end().parent().children(b?".thing:first":".thing:last")),a.filter(".stub").length&&g.push(a.thing_id()),j>=5&&g.length==0)break;g.length&&$.request("fetch_links",{links:g.join(","),listing:c.attr("id")})})})}function linkstatus(){return reddit.status_msg.submitting}function subscribe(a){return function(){reddit.logged?($.things(a).find(".entry").addClass("likes"),$.request("subscribe",{sr:a,action:"sub"})):showcover()}}
function unsubscribe(a){return function(){reddit.logged?($.things(a).find(".entry").removeClass("likes"),$.request("subscribe",{sr:a,action:"unsub"})):showcover()}}function friend(a,b,c){return function(){reddit.logged?(encoded=encodeURIComponent(reddit.referer),$.request("friend?note="+encoded,{name:a,container:b,type:c})):showcover()}}function unfriend(a,b,c){return function(){$.request("unfriend",{name:a,container:b,type:c})}}
function share(a){$.request("new_captcha");$(a).new_thing_child($(".sharelink:first").clone(!0).attr("id","sharelink_"+$(a).thing_id()),!1);$.request("new_captcha")}function cancelShare(a){return cancelToggleForm(a,".sharelink",".share-button")}function reject_promo(a){$(a).thing().find(".rejection-form").show().find("textare").focus()}function cancel_reject_promo(a){$(a).thing().find(".rejection-form").hide()}
function complete_reject_promo(a){$(a).thing().removeClass("accepted").addClass("rejected").find(".reject_promo").remove()}function helpon(a){$(a).parents(".usertext-edit:first").children(".markhelp:first").show()}function helpoff(a){$(a).parents(".usertext-edit:first").children(".markhelp:first").hide()}
function show_all_messages(a){var b=[];$(a).parents(".message").find(".entry .collapsed").hide().end().find(".noncollapsed, .midcol:first").filter(":hidden").each(function(){var a=$(this).show().thing_id();b.indexOf(a)==-1&&b.push(a)});b.length&&$.request("uncollapse_message",{id:b.join(",")});return!1}
function hide_all_messages(a){var b=[];$(a).parents(".message").find(".entry .collapsed").show().end().find(".noncollapsed, .midcol:first").filter(":visible").each(function(){var a=$(this).hide().thing_id();b.indexOf(a)==-1&&b.push(a)});b.length&&$.request("collapse_message",{id:b.join(",")});return!1}
function hidecomment(a){a=$(a).thing();a.hide().find(".noncollapsed:first, .midcol:first").hide().end().show().find(".entry:first .collapsed").show();a.hasClass("message")?$.request("collapse_message",{id:$(a).thing_id()}):a.find(".child:first").hide();return!1}
function showcomment(a){a=$(a).thing();a.find(".entry:first .collapsed").hide().end().find(".noncollapsed:first, .midcol:first").show().end().show();a.hasClass("message")?$.request("uncollapse_message",{id:$(a).thing_id()}):a.find(".child:first").show();return!1}function morechildren(a,b,c,e,g){$(a).html(reddit.status_msg.loading).css("color","red");a=$(a).parents(".thing.morechildren:first").thing_id();$.request("morechildren",{link_id:b,children:c,depth:e,id:a,pv_hex:g});return!1}
function moremessages(a){$(a).html(reddit.status_msg.loading).css("color","red");$.request("moremessages",{parent_id:$(a).thing_id()});return!1}
function update_reddit_count(a){if(a&&reddit.logged){var b=new Date,c=$.cookie_read("reddit_counts").data;if(!$.defined(c))c={},c._date=b.toString();var e=b-new Date(c._date)>864E5;c[a]=$.with_default(c[a],0)+1;var g=[];$.each(c,function(b){if(b!="_date"){if(e&&b!=a){var h=Math.floor(0.9*c[b]);h>0?c[b]=h:delete c[b]}c[b]&&g.push(b)}});g.sort(function(a,b){return c[b]-c[a]});e&&(c._date=b.toString());for(var b="",h=0;h<g.length;h++){var i=g[h];h<10?b+=g[h]+",":h>=100&&i!=a&&delete c[i]}$.cookie_write({name:"reddit_counts",
data:c});b&&$.cookie_write({name:"recent_reddits",data:b})}}function add_thing_to_cookie(a,b){var c=$(a).thing_id();if(c&&c.length)return add_thing_id_to_cookie(c,b)}function add_thing_id_to_cookie(a,b){var c=$.cookie_read(b);if(!c.data)c.data="";if(c.data.substring(0,a.length)!=a){c.data=a+","+c.data;if(c.data.length>1E3){var e=c.data.split(","),e=$.uniq(e,20);c.data=e.join(",")}$.cookie_write(c)}}
function clicked_items(){var a=$.cookie_read("recentclicks2");if(a&&a.data){for(var a=a.data.split(","),b=a.length-1;b>=0;b--)(!a[b]||!a[b].length)&&a.splice(b,1);return a}else return[]}function clear_clicked_items(){var a=$.cookie_read("recentclicks2");a.data="";$.cookie_write(a);$(".gadget").remove()}
function updateEventHandlers(a){var a=$(a),b=a.parent();$(a).filter(".promotedlink, .sponsorshipbox").bind("onshow",function(){var a=$(this).thing_id();if($.inArray(a,reddit.tofetch)!=-1)$.request("onload",{ids:reddit.tofetch.join(",")}),reddit.tofetch=[];var b=reddit.trackers[a];if($.defined(b)){var g=$(this).find("a.title"),h;$.browser.msie&&(h=g.html());$(this).find("a.title").attr("href",b.click).end().find("a.thumbnail").attr("href",b.click).end().find("img.promote-pixel").attr("src",b.show);
$.browser.msie&&h!=g.html()&&g.html(h);delete reddit.trackers[a]}}).filter(":visible").trigger("onshow");$(a).filter(".link").find("a.title, a.comments").mousedown(function(){var b=reddit.sr[$(this).thing_id()]||reddit.cur_site;update_reddit_count(b);$(this).addClass("click");add_thing_to_cookie(this,"recentclicks2");b=$(this).parents(".organic-listing").length>0;last_click(a,b)});b.filter(".organic-listing").length&&(a.find(".hide-button a, .del-button a.yes, .report-button a.yes").each(function(){$(this).get(0).onclick=
null}),a.find(".hide-button a").click(function(){var a=$(this).get(0);change_state(a,"hide",function(){get_organic(a,1)})}),a.find(".del-button a.yes").click(function(){var a=$(this).get(0);change_state(a,"del",function(){get_organic(a,1)})}),a.find(".report-button a.yes").click(function(){var a=$(this).get(0);change_state(a,"report",function(){get_organic(a,1)})}))}
function last_click(a,b){if(a){var c={href:window.location.href,what:$(a).thing_id(),organic:b};$.cookie_write({name:"last_thing",data:c})}else if((c=$.cookie_read("last_thing").data)&&c.href==window.location.href){var e=$(".organic-listing");c.organic&&e.length==1&&e.find(".thing:visible").thing_id()!=c.what&&(a=e.things(c.what),a.length>0&&!a.hasClass("stub")?(e.find(".thing:visible").hide(),a.show()):(a.remove(),e.find(".thing:visible").before('<div class="thing id-'+c.what+' stub" style="display: none"></div'),
$.request("fetch_links",{links:c.what,show:c.what,listing:e.attr("id")})));$.things(c.what).addClass("last-clicked");$.cookie_write({name:"last_thing",data:""})}}function login(){if(cnameframe)return!0;return post_user(this,"login")}function register(){if(cnameframe)return!0;return post_user(this,"register")}
function fetch_title(){var a=$("#url-field"),b=a.find(".NO_URL"),a=a.find(".title-status"),c=$("#url").val();c?(a.show().text(reddit.status_msg.loading),b.hide(),$.request("fetch_title",{url:c})):(a.hide(),b.show().text("a url is required"))}function sr_cache(){if(!$.defined(reddit.sr_cache))reddit.sr_cache=[];return reddit.sr_cache}function highlight_reddit(a){$("#sr-drop-down").children(".sr-selected").removeClass("sr-selected");a&&$(a).addClass("sr-selected")}
function update_dropdown(a){var b=$("#sr-drop-down");if(a.length){var c=b.children(":first");c.removeClass("sr-selected");b.children().remove();$.each(a,function(e){if(!(e>10)){var e=a[e],h=c.clone();h.text(e);b.append(h)}});var e=$("#sr-autocomplete").outerHeight();b.css("top",e);b.show()}else b.hide()}function sr_search(a){var a=a.toLowerCase(),b=sr_cache();b[a]?update_dropdown(b[a]):$.request("search_reddit_names",{query:a},function(c){b[a]=c.names;update_dropdown(c.names)})}
function sr_name_up(a){var b=$("#sr-autocomplete").val(),c=window.old_sr_name||"";window.old_sr_name=b;if(b=="")hide_sr_name_list();else if(!(a.keyCode==38||a.keyCode==40||a.keyCode==9))if(a.keyCode==27&&reddit.orig_sr)$("#sr-autocomplete").val(reddit.orig_sr),hide_sr_name_list();else if(b!=c)reddit.orig_sr=b,sr_search($("#sr-autocomplete").val())}
function sr_name_down(a){var b=$("#sr-autocomplete");if(a.keyCode==38||a.keyCode==40){var a=a.keyCode==38&&"up"||"down",c=$("#sr-drop-down .sr-selected:first"),e=$("#sr-drop-down .sr-name-row:first"),g=$("#sr-drop-down .sr-name-row:last"),h=null,h=a=="down"?c.length?c.get(0)==g.get(0)?null:c.next(":first"):e:c.length?c.get(0)==e.get(0)?null:c.prev(":first"):g;highlight_reddit(h);h?b.val($.trim(h.text())):b.val(reddit.orig_sr);return!1}else if(a.keyCode==13)return hide_sr_name_list(),b.parents("form").submit(),
!1}function hide_sr_name_list(){$("#sr-drop-down").hide()}function sr_dropdown_mdown(a){reddit.sr_mouse_row=a;return!1}function sr_dropdown_mup(a){reddit.sr_mouse_row==a&&(a=$(a).text(),$("#sr-autocomplete").val(a),$("#sr-drop-down").hide())}function set_sr_name(a){a=$(a).text();$("#sr-autocomplete").trigger("focus").val(a)}
function select_form_tab(a,b,c){a=$(a).parent();a.addClass("selected").siblings().removeClass("selected");a=a.parent("ul").next(".formtabs-content");a.find(b).show().find(":input").removeAttr("disabled").end();a.find(c).hide().find(":input").attr("disabled",!0)}function expando_cache(){if(!$.defined(reddit.thing_child_cache))reddit.thing_child_cache=[];return reddit.thing_child_cache}
function expando_child(a){var b=expando_cache(),c=$(a).thing();c.find(".expando-button").addClass("expanded").removeClass("collapsed").get(0).onclick=function(){unexpando_child(a)};var e=c.find(".expando"),g=c.thing_id()+"_cache";b[g]?e.html($.unsafe(b[g])):$.request("expando",{link_id:c.thing_id()},function(a){b[g]=a;e.html($.unsafe(a))},!1,"html");e.show();return!1}
function unexpando_child(a){var b=$(a).thing();b.find(".expando-button").addClass("collapsed").removeClass("expanded").get(0).onclick=function(){expando_child(a)};b.find(".expando").hide().empty()}
function show_edit_usertext(a){var b=a.find(".usertext-edit"),c=a.find(".usertext-body"),e=b.find("div > textarea"),g=Math.max(c.children(".md").width(),500),h=Math.max(c.children(".md").height(),100);c.hide();b.show();e.css("width","");e.css("height","");e.get(0).scrollHeight>e.height()&&(c=Math.max(g-5,e.width()),e.width(c),b.width(c),b=Math.max(h,e.height()),e.height(b));a.find(".cancel, .save").show().end().find(".help-toggle").show().end();e.focus()}
function hide_edit_usertext(a){a.find(".usertext-edit").hide().end().find(".usertext-body").show().end().find(".cancel, .save").hide().end().find(".help-toggle").hide().end().find(".markhelp").hide().end()}
function comment_reply_for_elem(a){var a=$(a),b=a.thing(),c=a.thing_id(),e=b.find(".child .usertext:first");if(!e.length||e.parent().thing_id()!=b.thing_id())e=$(".usertext.cloneable:first").clone(!0),a.new_thing_child(e),e.prop("thing_id").value=c,e.attr("id","commentreply_"+c),e.find(".error").hide();return e}function edit_usertext(a){a=$(a).thing();a.find(".edit-usertext:first").parent("li").andSelf().hide();show_edit_usertext(a.find(".usertext:first"))}
function cancel_usertext(a){a=$(a).thing().debug();a.find(".edit-usertext:first").parent("li").andSelf().show();hide_edit_usertext(a.find(".usertext:first"))}function save_usertext(a){$(a).thing().find(".edit-usertext:first").parent("li").andSelf().show()}function reply(a){var b=comment_reply_for_elem(a);show_edit_usertext(b);b.show();b.find(".cancel").get(0).onclick=function(){b.hide()};return!1}function toggle_distinguish_span(a){a=$(a).parents("form")[0];$(a).children().toggle()}
function set_distinguish(a,b){change_state(a,"distinguish/"+b);$(a).children().toggle()}function populate_click_gadget(){if($(".click-gadget").length){var a=clicked_items();a&&a.length&&(a=$.uniq(a,5),a.sort(),$.request("gadget/click/"+a.join(","),void 0,void 0,void 0,"json",!0))}}
var toolbar_p=function(a,b){this.toggle_linktitle=function(a){$(".title, .submit, .url, .linkicon").toggle();$(a).is(".pushed-button")?$(a).parents(".middle-side").removeClass("clickable"):($(a).parents(".middle-side").addClass("clickable"),$(".url").children("form").children("input").focus().select());return this.toggle_pushed(a)};this.toggle_pushed=function(a){a=$(a);a.is(".pushed-button")?a.removeClass("pushed-button").addClass("popped-button"):a.removeClass("popped-button").addClass("pushed-button");
return!1};this.push_button=function(a){$(a).removeClass("popped-button").addClass("pushed-button")};this.pop_button=function(a){$(a).removeClass("pushed-button").addClass("popped-button")};this.serendipity=function(){this.push_button(".serendipity");return!0};this.show_panel=function(){parent.inner_toolbar.document.body.cols=a};this.hide_panel=function(){parent.inner_toolbar.document.body.cols=b};this.resize_toolbar=function(){var a=$("body").height();parent.document.body.rows=a+"px, 100%"};this.login_msg=
function(){$(".toolbar-status-bar").show();$(".login-arrow").show();this.resize_toolbar();return!1};this.top_window=function(){for(var a=window;a!=a.parent;)a=a.parent;return a.parent};var c=null;this.panel_loadurl=function(a){try{return window.parent.inner_toolbar.reddit_panel.location==a?!1:(c!=null&&(this.pop_button(c),c=null),!0)}catch(b){return!0}};var e=0;this.comments_pushed=function(a){(e=!e)?(this.push_button(a),this.show_panel()):(this.pop_button(a),this.hide_panel())};this.gourl=function(a,
b){var c=$(a).find('input[type="text"]').val(),c=b+escape(c);this.top_window().location.href=c;return!1};this.pref_commentspanel_hide=function(){$.request("tb_commentspanel_hide")};this.pref_commentspanel_show=function(){$.request("tb_commentspanel_show")}};function clear_all_langs(a){$(a).parents("td").find('input[type="checkbox"]').prop("checked",!1)}function check_some_langs(a){$(a).parents("td").find("#some-langs").prop("checked",!0)}
function fetch_parent(a,b,c){$(a).css("color","red").html(reddit.status_msg.loading);var e=$(a).thing();if(e.find(".uncollapsed .parent").length==0){var g="";$.getJSON(b,function(b){$.each(b,function(){this&&this.data.children&&$.each(this.data.children,function(){if(this.data.name==c)g=this.data.body_html})});g&&e.find(".noncollapsed .md").before('<div class="parent rounded">'+$.unsafe(g)+"</div>");$(a).parent("li").andSelf().remove()})}return!1}
function big_mod_action(a,b){a.hasClass("pressed")||(a.addClass("pressed"),d={id:a.thing_id()},b==-1?($.request("remove",d,null,!0),a.siblings(".removed").show(),a.siblings(".approved").hide()):b==1&&($.request("approve",d,null,!0),a.siblings(".removed").hide(),a.siblings(".approved").show()));a.siblings(".pretty-button").removeClass("pressed");return!1}
function juryvote(a,b){var c=a.thing_id();a.hasClass("pressed")&&(b=0);a.toggleClass("pressed");a.siblings(".pretty-button").removeClass("pressed");d={id:c,dir:b};$.request("juryvote",d,null,!0);a.siblings(".thanks-for-voting").show();return!1}
$(function(){$("body").click(close_menus);$("body").set_thing_init(updateEventHandlers);"placeholder"in document.createElement("input")||$("textarea[placeholder], input[placeholder]").addClass("gray").each(function(){var a=$(this),b=a.attr("placeholder");a.val()==""&&a.val(b)});$("textarea.gray, input.gray").focus(function(){$(this).attr("rows",7).filter(".gray").removeClass("gray").val("")});reddit.logged&&$.cookie_name_prefix(reddit.logged);$.default_cookie_domain(reddit.cur_domain.split(":")[0]);
reddit.cur_site&&update_reddit_count(reddit.cur_site);last_click();$('#search input[name="q"]').focus(function(){$("#searchexpando").slideDown()});$("#search_showmore").click(function(a){$("#search_showmore").parent().hide();$("#moresearchinfo").slideDown();a.preventDefault()});$("#moresearchinfo").prepend('<a href="#" id="search_hidemore">[-]</a>');$("#search_hidemore").click(function(a){$("#search_showmore").parent().show();$("#moresearchinfo").slideUp();a.preventDefault()})});
function show_friend(a){$(".author.id-"+a).addClass("friend").next(".userattrs").each(function(){$(this).html()?$(this).find(".friend").length==0&&$(this).find("a:first").debug().before('<a class="friend" title="friend" href="/prefs/friends">F</a>,'):$(this).html(' [<a class="friend" title="friend" href="/prefs/friends">F</a>]')})}
function show_unfriend(a){$(".author.id-"+a).removeClass("friend").next(".userattrs").each(function(){$(this).find("a.friend").remove();$(this).find("a").length==0&&$(this).html("")})}
function search_feedback(a,b){f=$("form#search");var c=f.find('input[name="q"]').val(),e=f.find('input[name="sort"]').val(),g=f.find('input[name="t"]').val();$.request("searchfeedback",{q:c,sort:e,t:g,approval:b},null,!0);a.siblings(".pretty-button").removeClass("pressed");a.siblings(".thanks").show();a.addClass("pressed");return!1}function highlight_new_comments(a){var b;for(b=0;b<=9;b++)items=$(".comment-period-"+b),a>=0&&b>=a?items.addClass("new-comment"):items.removeClass("new-comment")};
r.strings = {}
